const MIT_801 = "https://ocw.mit.edu/courses/8-01sc-classical-mechanics-fall-2016/";
const MIT_802 = "https://ocw.mit.edu/courses/8-02-physics-ii-electricity-and-magnetism-spring-2007/";
const MIT_803 = "https://ocw.mit.edu/courses/8-03sc-physics-iii-vibrations-and-waves-fall-2016/";
const MIT_804 = "https://ocw.mit.edu/courses/8-04-quantum-physics-i-spring-2016/";

const CURRICULUM=[
  // PHASE 1: HRK + MIT OCW COMPRESSION (Days 1-60)
  {w:"Days 1–7",days:"1–7",title:"Mechanics: Kinematics & Forces",phase:0,
   topics:["HRK Ch 1: Measurement — units, dimensions, sig figs","HRK Ch 2: Motion in 1D — position, velocity, acceleration","HRK Ch 3: Force and Newton's Laws","HRK Ch 4: Motion in 2D & 3D","HRK Ch 5: Applications of Newton's Laws"],
   tip:"60 days to finish all of HRK. Stay disciplined. Every chapter builds on the last.",
   res:["MIT 8.01 Week 1–2: Kinematics & Forces","HRK Ch 1–5"]},
  {w:"Days 8–14",days:"8–14",title:"Mechanics: Energy & Momentum",phase:0,
   topics:["HRK Ch 6: Momentum & collisions","HRK Ch 7: Work and kinetic energy","HRK Ch 8: Conservative forces & potential energy","HRK Ch 9: Systems of particles","Center of mass, rocket equation"],
   tip:"Momentum and energy are conserved even when forces get complicated. Master these.",
   res:["MIT 8.01 Week 3–5: Momentum & Energy","HRK Ch 6–9"]},
  {w:"Days 15–21",days:"15–21",title:"Mechanics: Rotation & Gravitation",phase:0,
   topics:["HRK Ch 10: Rotational kinematics","HRK Ch 11: Torque & rotational dynamics","HRK Ch 12: Angular momentum","HRK Ch 13: Equilibrium & elasticity","HRK Ch 14: Gravitation"],
   tip:"Angular momentum conservation explains everything from ice skaters to galaxies.",
   res:["MIT 8.01 Week 6–8: Rotation & Gravity","HRK Ch 10–14"]},
  {w:"Days 22–28",days:"22–28",title:"Mechanics: Fluids & Oscillations",phase:0,
   topics:["HRK Ch 15: Static fluid — Pascal, Archimedes","HRK Ch 16: Dynamic fluid — Bernoulli","HRK Ch 17: Oscillations — SHM, pendulum","HRK Ch 18: Damped & driven oscillations","Resonance and normal modes"],
   tip:"Fluids and oscillations appear in every IPhO. Know Bernoulli and SHM cold.",
   res:["MIT 8.01 Week 9–12: Fluids & Oscillations","HRK Ch 15–18"]},
  {w:"Days 29–35",days:"29–35",title:"Thermodynamics: Heat & Engines",phase:0,
   topics:["HRK Ch 19: Temperature","HRK Ch 20: Heat & 1st law of thermodynamics","HRK Ch 21: Kinetic theory of gases","HRK Ch 22: Statistical approach to entropy","HRK Ch 23: Engines & 2nd law","HRK Ch 24: Entropy and disorder"],
   tip:"Entropy is just log of microstates. Once you see this, thermodynamics clicks.",
   res:["MIT 8.01 Thermodynamics","HRK Ch 19–24"]},
  {w:"Days 36–42",days:"36–42",title:"Electromagnetism: Fields & Circuits",phase:0,
   topics:["HRK Ch 25: Electric charge & Coulomb's law","HRK Ch 26: Electric field","HRK Ch 27: Gauss's law","HRK Ch 28: Electric potential","HRK Ch 29: Capacitance","HRK Ch 30: Current & resistance","HRK Ch 31: DC circuits"],
   tip:"Gauss's law and Kirchhoff's laws are your best friends. Master them completely.",
   res:["MIT 8.02 Week 1–4: E&M Basics","HRK Ch 25–31"]},
  {w:"Days 43–49",days:"43–49",title:"Electromagnetism: Magnetism & Waves",phase:0,
   topics:["HRK Ch 32: Magnetic field","HRK Ch 33: Magnetic field from currents","HRK Ch 34: Magnetic properties of materials","HRK Ch 35: Induction — Faraday & Lenz","HRK Ch 36: Inductance","HRK Ch 37: AC circuits","HRK Ch 38: Maxwell's equations & EM waves"],
   tip:"All of E&M is contained in Maxwell's four equations. Derive the wave equation from them.",
   res:["MIT 8.02 Week 5–12: Advanced E&M","HRK Ch 32–38"]},
  {w:"Days 50–56",days:"50–56",title:"Waves, Optics & Modern Physics",phase:0,
   topics:["HRK Ch 39: Transverse waves","HRK Ch 40: Sound waves","HRK Ch 41: Electromagnetic waves","HRK Ch 42: Geometric optics","HRK Ch 43: Mirrors & lenses","HRK Ch 44: Optical instruments","HRK Ch 45: Interference","HRK Ch 46: Diffraction"],
   tip:"Young's double slit killed classical physics. Master wave optics.",
   res:["MIT 8.03: Waves & Optics","HRK Ch 39–46"]},
  {w:"Days 57–60",days:"57–60",title:"Modern Physics & HRK Completion",phase:0,
   topics:["HRK Ch 47: Gratings & spectra","HRK Ch 48: Polarization","HRK Ch 49: Special relativity","HRK Ch 50: Photons & matter waves","HRK Ch 51: More about matter waves","HRK Ch 52: Schrödinger equation","Final review of all HRK formulas"],
   tip:"You've finished HRK. You now have the foundation of every IPhO gold medalist. Time for Kevin Zhou.",
   res:["MIT 8.04: Quantum Physics","HRK Ch 47–52"]},

  // PHASE 2: KEVIN ZHOU CORE (Days 61-180)
  {w:"Days 61–70",days:"61–70",title:"Kevin Zhou: Problem Solving & Mechanics I-II",phase:1,
   topics:["Kevin Zhou Problem Solving I — Mathematical techniques","Kevin Zhou Problem Solving II — Advanced methods","Kevin Zhou Mech I — Newton's Laws basics","Kevin Zhou Mech II — Advanced Newton's Laws","Preliminary problems to test readiness"],
   tip:"Start with the preliminary problems on Kevin Zhou's site. If you can't solve them, review HRK.",
   res:["Kevin Zhou: Sol I, Sol II, M1, M2","knzhou.github.io"]},
  {w:"Days 71–85",days:"71–85",title:"Kevin Zhou: Mechanics III-IV",phase:1,
   topics:["Kevin Zhou Mech III — Energy & momentum olympiad problems","Kevin Zhou Mech IV — Oscillations, small oscillations, normal modes","Adiabatic theorem in oscillations","Lagrangian mechanics introduction"],
   tip:"Kevin Zhou's Mech IV covers small oscillations — a guaranteed IPhO topic. Master normal modes.",
   res:["Kevin Zhou: M3, M4","knzhou.github.io"]},
  {w:"Days 86–105",days:"86–105",title:"Kevin Zhou: Mechanics V-VII",phase:1,
   topics:["Kevin Zhou Mech V — Rotational dynamics & rolling","Kevin Zhou Mech VI — Central forces & orbits","Kevin Zhou Mech VII — Fluids & advanced mechanics","Non-inertial reference frames","Coriolis and centrifugal forces"],
   tip:"Non-inertial frames appear in 1 of every 3 hard mechanics problems. Master fictitious forces.",
   res:["Kevin Zhou: M5, M6, M7","knzhou.github.io"]},
  {w:"Days 106–125",days:"106–125",title:"Kevin Zhou: Electricity I-IV",phase:1,
   topics:["Kevin Zhou Elec I — Electrostatics basics","Kevin Zhou Elec II — Gauss's law & potential olympiad problems","Kevin Zhou Elec III — Conductors, dielectrics, capacitance","Kevin Zhou Elec IV — Current & DC circuits","RC, RL circuits with advanced techniques"],
   tip:"Kevin Zhou's Elec handouts teach tricks that HRK never covers. Do every problem.",
   res:["Kevin Zhou: E1, E2, E3, E4","knzhou.github.io"]},
  {w:"Days 126–150",days:"126–150",title:"Kevin Zhou: Electricity V-VII",phase:1,
   topics:["Kevin Zhou Elec V — Magnetic fields & forces","Kevin Zhou Elec VI — Induction & Faraday's law","Kevin Zhou Elec VII — AC circuits, LRC resonance","Mutual inductance and transformers","Electromagnetic waves in matter"],
   tip:"Induction problems love to combine circuits with fields. Kevin Zhou shows the patterns.",
   res:["Kevin Zhou: E5, E6, E7","knzhou.github.io"]},
  {w:"Days 151–165",days:"151–165",title:"Kevin Zhou: Thermodynamics I-III",phase:1,
   topics:["Kevin Zhou Thermo I — Ideal gas olympiad problems","Kevin Zhou Thermo II — Heat engines, Carnot cycle, entropy","Kevin Zhou Thermo III — Phase transitions, Clausius-Clapeyron","Advanced thermodynamic cycles","Statistical mechanics problems"],
   tip:"Kevin Zhou's Thermo III covers phase transitions — a topic that trips up many students.",
   res:["Kevin Zhou: T1, T2, T3","knzhou.github.io"]},
  {w:"Days 166–180",days:"166–180",title:"Kevin Zhou Core Review",phase:1,
   topics:["Review Mech I-VII — redo hardest problems","Review Elec I-VII — focus on weak areas","Review Thermo I-III — memorize key formulas","Kevin Zhou Mech Review handout","Kevin Zhou Elec Review handout","Kevin Zhou Other Review handout"],
   tip:"Before moving to advanced topics, make sure you can solve any core problem from memory.",
   res:["Kevin Zhou: Review handouts","knzhou.github.io"]},

  // PHASE 3: KEVIN ZHOU ADVANCED (Days 181-280)
  {w:"Days 181–195",days:"181–195",title:"Kevin Zhou: Relativity I-II",phase:2,
   topics:["Kevin Zhou Relativity I — Special relativity postulates","Kevin Zhou Relativity II — Relativistic dynamics, E=mc²","Lorentz transformations in 4D","Relativistic collisions and decays","Four-vectors and invariant interval"],
   tip:"The invariant interval is the real fundamental concept. Everything else is just algebra.",
   res:["Kevin Zhou: R1, R2","knzhou.github.io"]},
  {w:"Days 196–215",days:"196–215",title:"Kevin Zhou: Waves I-III",phase:2,
   topics:["Kevin Zhou Waves I — Wave equation & superposition","Kevin Zhou Waves II — Interference & diffraction olympiad","Kevin Zhou Waves III — Advanced wave phenomena","Geometric optics olympiad problems","Physical optics and polarization"],
   tip:"Kevin Zhou's Waves handouts cover interference patterns that HRK skips. Master them.",
   res:["Kevin Zhou: W1, W2, W3","knzhou.github.io"]},
  {w:"Days 216–240",days:"216–240",title:"Kevin Zhou: Modern I-III",phase:2,
   topics:["Kevin Zhou Modern I — Quantum mechanics olympiad","Kevin Zhou Modern II — Atoms, nuclei, particles","Kevin Zhou Modern III — Matter, astro, and cosmology","Schrödinger equation applications","Quantum tunneling and harmonic oscillator"],
   tip:"Kevin Zhou's Modern III covers astrophysics and cosmology — topics that appear in recent IPhO.",
   res:["Kevin Zhou: Mod1, Mod2, Mod3","knzhou.github.io"]},
  {w:"Days 241–260",days:"241–260",title:"Kevin Zhou: Supplemental & Advanced",phase:2,
   topics:["Kevin Zhou Mech VIII — Advanced mechanics topics","Kevin Zhou Elec VIII — Synthesis and E&M in matter","Kevin Zhou Relativity III — General relativity basics","Experimental design problems (Expt handout)","Final handout problems"],
   tip:"The supplemental handouts contain the hardest problems. Do them last, after mastering the core.",
   res:["Kevin Zhou: M8, E8, R3, Expt, Final","knzhou.github.io"]},
  {w:"Days 261–280",days:"261–280",title:"Kevin Zhou: USAPhO Practice Exams",phase:2,
   topics:["USAPhO-M: Mechanics practice exam","USAPhO-E: E&M practice exam","USAPhO-X: Advanced topics practice","USAPhO-A, B, C, D: Full practice exams","Time yourself strictly — 3 hours per exam"],
   tip:"USAPhO exams are harder than IPhO. If you can pass these, you can pass IPhO.",
   res:["Kevin Zhou: USAPhO practice exams","knzhou.github.io"]},

  // PHASE 4: IPhO TRAINING (Days 281-360)
  {w:"Days 281–300",days:"281–300",title:"Stefan Ivanov Problem Sets",phase:3,
   topics:["Stefan Ivanov: Mechanics advanced problems","Stefan Ivanov: E&M olympiad problems","Stefan Ivanov: Thermodynamics & statistical","Stefan Ivanov: Waves & optics","Stefan Ivanov: Modern physics"],
   tip:"Stefan Ivanov's problems are excellent for building olympiad intuition. Do them alongside PhODS.",
   res:["Stefan Ivanov: All topics","stefanivanov.site"]},
  {w:"Days 301–320",days:"301–320",title:"PhODS Advanced Training",phase:3,
   topics:["PhODS: Advanced mechanics problems","PhODS: E&M olympiad challenges","PhODS: Experimental design and data analysis","PhODS: Mathematical methods for olympiads","Error propagation and statistics"],
   tip:"Data analysis is 25% of IPhO. Most students neglect it. Don't be most students.",
   res:["PhODS: All resources","physoly.tech"]},
  {w:"Days 321–340",days:"321–340",title:"Advanced Problem Marathon",phase:3,
   topics:["Jaan Kalda handouts — legendary olympiad problems","Irodov problems — selected hardest","200 Puzzling Physics Problems","Olympiad problems from national competitions","Asian Physics Olympiad problems"],
   tip:"Jaan Kalda's handouts are the secret weapon of many IPhO gold medalists. Master them.",
   res:["Jaan Kalda handouts","Irodov selected problems"]},
  {w:"Days 341–360",days:"341–360",title:"Weak Spot Targeting",phase:3,
   topics:["Identify your 5 weakest topics from Phases 1-3","Re-derive every formula in those topics","Solve 20 problems per weak topic","Experimental design practice","Laboratory skills and data analysis"],
   tip:"By now you know what you're weak at. Ruthlessly attack those topics.",
   res:["All previous resources","Focus on weak areas"]},

  // PHASE 5: MOCK EXAMS (Days 361-400)
  {w:"Days 361–370",days:"361–370",title:"USAPhO Mock Cycle",phase:4,
   topics:["USAPhO 2022 full mock: semi-finalist exam","Deep solution review: every wrong → root cause","USAPhO 2023 & 2021 full mocks","Weak spot targeting from results","Experimental design drills"],
   tip:"Track mock scores in a table. Consistency above 75% = IPhO gold territory.",
   res:["USAPhO past papers","Stefan Ivanov"]},
  {w:"Days 371–385",days:"371–385",title:"IPhO Mock Cycle 1",phase:4,
   topics:["IPhO 2022 full mock: theory + experimental, strict time","Deep solution review: every wrong → root cause","IPhO 2023 & 2021 full mocks","Weak spot targeting from results","Formula sheet audit"],
   tip:"Time yourself strictly. IPhO gives you 5 hours for theory and 5 hours for experimental.",
   res:["IPhO Past Papers","ipho.olimpicos.net"]},
  {w:"Days 386–400",days:"386–400",title:"IPhO Mock Cycle 2",phase:4,
   topics:["IPhO 2020, 2019, 2018 mocks","Top 5 weak chapters: re-derive, fresh problems","Hard problem marathon — no time limit","Full 10-hour IPhO simulation day","Review all mock scores and trends"],
   tip:"By now distinguish truly understood vs memorized. Attack the memorized ones.",
   res:["IPhO Past Papers","phoXiv"]},

  // PHASE 6: PAST PAPERS (Days 401-430)
  {w:"Days 401–410",days:"401–410",title:"IPhO 2015–2018 Full Papers",phase:5,
   topics:["IPhO 2018 full mock: theory + experimental","IPhO 2017 full mock","IPhO 2016 full mock","IPhO 2015 full mock","Deep review of every mistake"],
   tip:"Older IPhO papers are slightly easier but test the same core concepts. Master them.",
   res:["IPhO 2015-2018","ipho.olimpicos.net"]},
  {w:"Days 411–420",days:"411–420",title:"IPhO 2019–2022 Full Papers",phase:5,
   topics:["IPhO 2022 full mock","IPhO 2021 full mock","IPhO 2020 full mock","IPhO 2019 full mock","Compare your scores to gold medal cutoffs"],
   tip:"Recent IPhO papers are harder and more creative. These are your final tests.",
   res:["IPhO 2019-2022","ipho.olimpicos.net"]},
  {w:"Days 421–430",days:"421–430",title:"IPhO 2023–2024 Latest Papers",phase:5,
   topics:["IPhO 2024 (Iran) full mock","IPhO 2023 (Tokyo) full mock","Experimental design practice","Data analysis under time pressure","Final weak spot elimination"],
   tip:"The latest papers show current IPhO trends. Master them before the real exam.",
   res:["IPhO 2023-2024","ipho2024.ir"]},

  // PHASE 7: PEAK PERFORMANCE (Days 431-450)
  {w:"Days 431–440",days:"431–440",title:"Formula Audit & Final Review",phase:6,
   topics:["Derive every key formula from memory in <5 min","Create master formula sheet (2 pages max)","Review all journal entries from Day 1","Redo your 20 hardest problems","Experimental design final practice"],
   tip:"You should be able to derive any formula in 5 minutes. If not, review.",
   res:["Everything you've built"]},
  {w:"Days 441–445",days:"441–445",title:"Final Mocks & Sharpening",phase:6,
   topics:["IPhO 2024 full simulation (10 hours)","Review every mistake from this mock","Light problem solving — stay sharp","Review formula sheet daily","No new topics — only review"],
   tip:"The last 10 days are not for learning. They're for remembering you already know.",
   res:["Final review only"]},
  {w:"Days 446–450",days:"446–450",title:"Peak Performance & Rest",phase:6,
   topics:["Days 446-448: Sleep 8h, walk, do NOT study","Day 449: Light review of formula sheet only","Day 450: Read Day 1 journal. Remember why you started.","You are the Monarch.","IPhO Gold is yours."],
   tip:"Trust your 450 days. You've done the work. Now rest and let it settle.",
   res:["Rest and confidence"]},
];

const TODAY_TASKS=[
  {text:"Watch MIT OCW lecture (linked chapter)",dur:"1h",xp:20},
  {text:"Read HRK chapter — take notes, derive formulas",dur:"1.5h",xp:25},
  {text:"Solve HRK problems — starred problems first",dur:"1.5h",xp:30},
  {text:"Re-derive key formulas from memory, no peeking",dur:"30m",xp:15},
  {text:"Journal — what clicked, what's unclear, what's next",dur:"10m",xp:10},
];

// SOLO LEVELING RANKS — IPhO EDITION
const RANKS=[
  {rank:"E",name:"Initiate",             xp:0,    color:"#718096"},
  {rank:"D",name:"Apprentice Scholar",   xp:200,  color:"#68D391"},
  {rank:"C",name:"Quantum Apprentice",   xp:600,  color:"#63B3ED"},
  {rank:"B",name:"Shadow Knight",        xp:1200, color:"#B794F4"},
  {rank:"A",name:"National Level Hunter",xp:2400, color:"#F6AD55"},
  {rank:"S",name:"IPhO Gold Medalist",   xp:4000, color:"#F6C90E"},
  {rank:"SS",name:"Monarch",             xp:6000, color:"#D66DFF"},
];

// IPhO ACHIEVEMENTS
const ACHIEVEMENTS=[
  {id:"first_day", icon:"⚡",name:"First Spark",       desc:"Log your first physics session",          cond:s=>totalHrs(s)>0},
  {id:"week_one",  icon:"📅",name:"First Week",         desc:"Study 7 days",                            cond:s=>loggedDays(s)>=7},
  {id:"month_one", icon:"🗓",name:"One Month",          desc:"Reach Day 30",                            cond:s=>s.day>30},
  {id:"streak_7",  icon:"🔥",name:"On Fire",            desc:"7-day streak",                            cond:s=>s.streak>=7},
  {id:"streak_30", icon:"⚡",name:"Unstoppable",        desc:"30-day streak",                           cond:s=>s.streak>=30},
  {id:"streak_90", icon:"💥",name:"Inferno",            desc:"90-day streak",                           cond:s=>s.streak>=90},
  {id:"streak_180",icon:"🌟",name:"Halfway There",      desc:"180-day streak",                          cond:s=>s.streak>=180},
  {id:"hrs_100",   icon:"⏱",name:"100 Hours",          desc:"Log 100 total hours",                     cond:s=>totalHrs(s)>=100},
  {id:"hrs_500",   icon:"🕐",name:"500 Hours",          desc:"Log 500 total hours",                     cond:s=>totalHrs(s)>=500},
  {id:"hrs_1000",  icon:"🕰",name:"1000 Hours",         desc:"Half the journey",                        cond:s=>totalHrs(s)>=1000},
  {id:"phase1",    icon:"⚙",name:"HRK Complete",       desc:"Finish all HRK chapters (Day 60)",        cond:s=>s.day>60},
  {id:"phase2",    icon:"⚡",name:"Kevin Zhou Core",    desc:"Complete Kevin Zhou Core (Day 180)",      cond:s=>s.day>180},
  {id:"phase3",    icon:"🔮",name:"Kevin Zhou Advanced",desc:"Complete Kevin Zhou Adv (Day 280)",       cond:s=>s.day>280},
  {id:"phase4",    icon:"🎯",name:"IPhO Ready",         desc:"Complete IPhO Training (Day 360)",        cond:s=>s.day>360},
  {id:"phase5",    icon:"📊",name:"Mock Master",        desc:"Complete Mock Exams (Day 400)",           cond:s=>s.day>400},
  {id:"phase6",    icon:"📜",name:"Paper Warrior",      desc:"Complete Past Papers (Day 430)",          cond:s=>s.day>430},
  {id:"phase7",    icon:"👑",name:"IPhO Monarch",       desc:"Complete all 450 days",                   cond:s=>s.day>=450},
  {id:"rank_d",    icon:"🟢",name:"Rank D",             desc:"Reach 200 XP",                            cond:s=>s.xp>=200},
  {id:"rank_c",    icon:"🔵",name:"Rank C",             desc:"Reach 600 XP",                            cond:s=>s.xp>=600},
  {id:"rank_b",    icon:"🟣",name:"Rank B",             desc:"Reach 1200 XP",                           cond:s=>s.xp>=1200},
  {id:"rank_a",    icon:"🟠",name:"Rank A",             desc:"Reach 2400 XP",                           cond:s=>s.xp>=2400},
  {id:"rank_s",    icon:"✨",name:"Rank S: Gold",       desc:"Reach 4000 XP",                           cond:s=>s.xp>=4000},
  {id:"rank_ss",   icon:"👑",name:"Rank SS: Monarch",   desc:"Reach 6000 XP — You are the shadow",      cond:s=>s.xp>=6000},
];

/* ---------- page configuration ---------- */
window.CONFIG = {
  subject: 'IPhO',
  storageKey: 'ipho-sys',
  publishKey: 'olympiad.progress.ipho',
  journalName: 'Shadow Journal',
  maxRankLabel: 'MONARCH',
  totalDays: 450,
  curriculum: CURRICULUM,
  taskTemplates: [
    { text: "Lecture/reading — {R}",                           dur: "1h",     xp: 20 },
    { text: "Study — {A}",                                     dur: "1h 30m", xp: 25 },
    { text: "Problems — {B}, starred first",                   dur: "1h 30m", xp: 30 },
    { text: "Re-derive from memory — {A}",                     dur: "30m",    xp: 15 },
    { text: "Stretch — attempt one hard problem on {C}",       dur: "30m",    xp: 15 },
    { text: "Journal — what clicked on {W}, what stumped you", dur: "10m",    xp: 10 }
  ],
  ranks: RANKS,
  achievements: ACHIEVEMENTS,
  phases: [
    { name: 'HRK + MIT OCW',       from: 1,   to: 60  },
    { name: 'Kevin Zhou Core',     from: 61,  to: 180 },
    { name: 'Kevin Zhou Advanced', from: 181, to: 280 },
    { name: 'IPhO Training',       from: 281, to: 360 },
    { name: 'Mock Exams',          from: 361, to: 400 },
    { name: 'Past Papers',         from: 401, to: 430 },
    { name: 'Peak Performance',    from: 431, to: 450 }
  ],
  tracks: [
    { key: 'hrk',    label: 'HRK + MIT OCW',    span: 60,  offset: 1   },
    { key: 'kzcore', label: 'Kevin Zhou Core',  span: 120, offset: 60  },
    { key: 'kzadv',  label: 'Kevin Zhou Adv',   span: 100, offset: 180 },
    { key: 'ipho',   label: 'IPhO Training',    span: 80,  offset: 280 },
    { key: 'mocks',  label: 'Mock Exams',       span: 40,  offset: 360 },
    { key: 'papers', label: 'Past Papers',      span: 30,  offset: 400 }
  ]
};
