const CURRICULUM=[
  {w:"Weeks 1–2",days:"1–14",title:"Math & calculus foundation",phase:0,
   topics:["Trigonometry & spherical identities","Vectors, dot & cross products","Derivatives & chain rule","Integrals & substitution","First-order ODEs"],
   tip:"Don't rush. Every stellar physics formula needs calculus. A week here saves 3 weeks of confusion later.",
   res:["3Blue1Brown — Essence of Calculus","Khan Academy Calculus 1","Paul's Online Math Notes"]},
  {w:"Week 3",days:"15–21",title:"The celestial sphere",phase:0,
   topics:["Great circles & spherical triangles","Spherical excess formula","Zenith, nadir, celestial poles","Celestial equator geometry"],
   tip:"Draw everything. Spherical geometry lives in spatial intuition, not on the page.",
   res:["AO Guide: Positional — Sphere"]},
  {w:"Weeks 4–5",days:"22–35",title:"Coordinate systems",phase:0,
   topics:["Horizon & Equatorial coords (Alt-Az, RA/Dec)","Ecliptic & Galactic coords","Rotation matrix transforms","Rising/setting/transit conditions","Circumpolar star conditions"],
   tip:"Most-tested IOAA topic. Master coordinate transforms cold. Do 20+ problems minimum.",
   res:["AO Guide: Coordinate Systems","Aniket Sule Ch.2"]},
  {w:"Weeks 6–7",days:"36–49",title:"Timekeeping",phase:0,
   topics:["Solar vs sidereal time","Julian dates & calendars","LST, GST, UT conversions","Precession & nutation"],
   tip:"Derive the LST–RA relationship yourself from scratch. If you can't, you don't know it.",
   res:["AO Guide: Time","Aniket Sule Ch.3"]},
  {w:"Weeks 8–9",days:"50–63",title:"Perturbations & SSO basics",phase:0,
   topics:["Atmospheric refraction","Annual & diurnal parallax","Aberration of light","Solar & lunar motion","Eclipse geometry — umbra/penumbra"],
   tip:"Aberration of light: draw the velocity vector diagram. The geometry is everything.",
   res:["AO Guide: Perturbations & SSO"]},
  {w:"Weeks 10–11",days:"64–77",title:"Radiometry & magnitude systems",phase:0,
   topics:["Flux, luminosity, solid angle","Pogson magnitude formula","Distance modulus m−M=5log(d/10pc)","Color index B−V","Extinction & reddening E(B−V)"],
   tip:"The distance modulus appears in almost every IOAA problem. Derive it until it feels obvious.",
   res:["AO Guide: Radiometry","Aniket Sule Ch.5"]},
  {w:"Weeks 12–13",days:"78–91",title:"Blackbody radiation & telescopes",phase:0,
   topics:["Planck function — derive from scratch","Wien's displacement law derivation","Stefan-Boltzmann law","Telescope focal length, f-ratio, plate scale","Resolving power — Rayleigh criterion"],
   tip:"Derive Wien's law by differentiating Planck and setting to zero. This exact step appears in IOAA.",
   res:["AO Guide: Radiation & Telescopes","Aniket Sule Ch.6"]},
  {w:"Weeks 14–15",days:"92–105",title:"Kepler's laws from first principles",phase:1,
   topics:["Conservation of energy & angular momentum","Kepler 1st: central force → conic sections","Kepler 2nd: equal areas from L conservation","Kepler 3rd: T²∝a³ derivation"],
   tip:"Never memorize. Derive K3 until it takes under 2 minutes. That is mastery.",
   res:["AO Guide: Kepler's Laws","Feynman Lectures"]},
  {w:"Weeks 16–18",days:"106–126",title:"Bound orbits & orbital energy",phase:1,
   topics:["Vis-viva: v²=GM(2/r−1/a)","Elliptical orbit geometry","Perihelion & aphelion velocities","Escape velocity derivation","Tidal forces & Roche limit"],
   tip:"Vis-viva is to orbital mechanics what F=ma is to dynamics. Derive it every time.",
   res:["AO Guide: Bound Orbits","Aniket Sule Ch.7"]},
  {w:"Weeks 19–20",days:"127–140",title:"Unbound orbits & orbital elements",phase:1,
   topics:["Hyperbolic & parabolic orbits","6 orbital elements: a, e, i, Ω, ω, M","True vs eccentric vs mean anomaly","Kepler's equation M=E−e sinE"],
   tip:"Kepler's equation has no closed form. Practice iterative solving — IOAA asks for this.",
   res:["AO Guide: Unbound Orbits"]},
  {w:"Weeks 21–23",days:"141–161",title:"Three-body & orbital maneuvers",phase:1,
   topics:["Lagrange points L1–L5","Hill sphere derivation","Hohmann transfer orbit","Gravity assist — frame-switching argument","GR basics: Schwarzschild radius, gravitational redshift"],
   tip:"Gravity assist confuses people. Master the frame-switching energy argument completely.",
   res:["AO Guide: Three-Body & Maneuvers"]},
  {w:"Weeks 24–26",days:"162–182",title:"Stellar structure & classification",phase:1,
   topics:["Hydrostatic equilibrium derivation","Radiative vs convective transport","pp chain & CNO cycle","OBAFGKM spectral classification","HR diagram: physical meaning of each region"],
   tip:"The HR diagram is a map of stellar physics, not just a plot. Know why every region exists.",
   res:["AO Guide: Stellar Structure","Carroll & Ostlie Ch.10"]},
  {w:"Weeks 27–29",days:"183–203",title:"Binary star systems",phase:1,
   topics:["Visual, spectroscopic & eclipsing binaries","Radial velocity curve analysis","Eclipsing light curve analysis","Mass & radius determination","Mass transfer & Roche lobes"],
   tip:"Eclipsing binary light curve analysis is a guaranteed IOAA data problem. Master this cold.",
   res:["AO Guide: Binary Systems","Aniket Sule Ch.9"]},
  {w:"Weeks 30–34",days:"204–238",title:"Stellar evolution",phase:1,
   topics:["Pre-MS: Hayashi track, KH timescale","Main sequence lifetime t~M/L","Post-MS low mass: RGB, He-flash, AGB","Post-MS high mass: supergiants, iron core","WD (Chandrasekhar 1.4M☉), NS, BH","Type Ia vs core-collapse supernovae","First IOAA past papers (2012–2015)"],
   tip:"Chandrasekhar 1.4M☉ — know the quantum pressure order-of-magnitude derivation.",
   res:["AO Guide: Stellar Evolution","Carroll & Ostlie Ch.13"]},
  {w:"Weeks 35–37",days:"239–259",title:"Solar system & practical sky",phase:2,
   topics:["Planetary atmospheres: scale height, escape","Tides & tidal locking","Asteroids, comets, meteors","All 88 constellation memorization sprint","Top 50 bright stars: RA/Dec, spectral type"],
   tip:"Start Stellarium daily. 15 min identification of the night sky. Every single day.",
   res:["AO Guide: SSO & Practical","Stellarium"]},
  {w:"Weeks 38–40",days:"260–280",title:"Galaxies & galactic astrophysics",phase:2,
   topics:["Hubble morphological sequence","Milky Way: disk, bulge, halo, spiral arms","Galactic rotation — Oort constants A & B","Flat rotation curve → dark matter","Distance ladder: parallax → Cepheids → SN Ia","AGN: Seyfert, quasars, blazars, unified model"],
   tip:"v=√(GM/r) predicts declining v but we observe flat. Know the dark matter argument quantitatively.",
   res:["AO Guide: Galactic Astrophysics"]},
  {w:"Weeks 41–43",days:"281–301",title:"Cosmology",phase:2,
   topics:["Hubble's law: v=H₀d","FRW metric & scale factor a(t)","Friedmann equations — derive from Newtonian","Ω, flat/open/closed universes","BBN, recombination, CMB timeline","Dark energy & ΛCDM model"],
   tip:"Derive Friedmann from Newtonian gravity applied to a uniform sphere. The GR term is just a constant.",
   res:["AO Guide: Cosmology","Ned Wright's Tutorial"]},
  {w:"Weeks 44–46",days:"302–322",title:"Advanced topics",phase:2,
   topics:["Gravitational waves: chirp mass, quadrupole","Eddington luminosity: L_Edd≈1.3×10³¹(M/M☉)W","Stellar oscillations & helioseismology","ISM: HII regions, Strömgren sphere","IOAA 2019–2024 hardest problems"],
   tip:"Eddington luminosity: set radiation pressure = gravity. It appears in 1 of every 3 hard IOAA problems.",
   res:["AO Guide: Advanced Topics"]},
  {w:"Weeks 47–51",days:"323–357",title:"Data analysis intensive",phase:2,
   topics:["Least squares & log-log plot fitting","Error propagation from partial derivatives","Photometric period finding","Spectroscopic RV extraction","IOAA data papers 2012–2022 (timed)","Chi-squared test & statistics","Calculator speed drills"],
   tip:"Data analysis = 25% of your final score. Most students neglect it. Don't.",
   res:["IOAA Official Past Papers"]},
  {w:"Weeks 52–55",days:"358–385",title:"Mock exam cycle 1",phase:3,
   topics:["IOAA 2022 full mock: theory + data, strict time","Deep solution review: every wrong → root cause","Weak spot targeting from results","IOAA 2023 & 2021 full mocks","Observation: constellation & Messier drills"],
   tip:"Track mock scores in a table. Trend matters. Consistency above 70% theory = gold territory.",
   res:["ioaa.net/problems"]},
  {w:"Weeks 56–59",days:"386–413",title:"Mock cycle 2 & final gaps",phase:3,
   topics:["IOAA 2020, 2019, 2018 mocks","Top 5 weak chapters: re-derive, fresh problems","Hard problem marathon — no time limit","88 constellations blind on blank map <10 min","Binary full review: light curve + RV combined"],
   tip:"By now distinguish truly understood vs memorized. Ruthlessly attack the memorized ones.",
   res:["aoxiv.aoguide.app"]},
  {w:"Weeks 60–64",days:"414–450",title:"Peak performance & sharpening",phase:3,
   topics:["IOAA 2017, 2016, 2015 full mocks","Formula audit: derive every key formula <5 min","Observation final sprint: all Messier blind","Data analysis sprint: 3 papers back to back","Days 442–444: sleep 8h, walk, do NOT study","Day 450: read Day 1 notes. Remember why you started."],
   tip:"The last week is not for learning. It's for remembering you already know. Trust your 450 days.",
   res:["Everything you've built"]},
];

const TODAY_TASKS=[
  {text:"Theory — AO Guide + Aniket Sule (today's chapter)",dur:"2h",xp:20},
  {text:"Derivations — reproduce every formula from memory, no peeking",dur:"45m",xp:15},
  {text:"Practice problems — easy → medium → IOAA style",dur:"1h",xp:25},
  {text:"Observation — Stellarium, 15 min constellation practice",dur:"15m",xp:10},
  {text:"Journal — what clicked, what's unclear, what's next",dur:"5m",xp:10},
];

const RANKS=[
  {rank:"E",name:"Initiate",       xp:0,    color:"#718096"},
  {rank:"D",name:"Observer",       xp:200,  color:"#68D391"},
  {rank:"C",name:"Analyst",        xp:600,  color:"#63B3ED"},
  {rank:"B",name:"Theorist",       xp:1200, color:"#B794F4"},
  {rank:"A",name:"Astrophysicist", xp:2400, color:"#F6AD55"},
  {rank:"S",name:"IOAA Gold",      xp:4000, color:"#F6C90E"},
];

const ACHIEVEMENTS=[
  {id:"first_day", icon:"🌅",name:"Day One",         desc:"Log your first session",          cond:s=>totalHrs(s)>0},
  {id:"week_one",  icon:"📅",name:"First Week",       desc:"Study 7 days",                    cond:s=>loggedDays(s)>=7},
  {id:"month_one", icon:"🗓",name:"One Month",        desc:"Reach Day 30",                    cond:s=>s.day>30},
  {id:"streak_7",  icon:"🔥",name:"On Fire",          desc:"7-day streak",                    cond:s=>s.streak>=7},
  {id:"streak_30", icon:"⚡",name:"Unstoppable",      desc:"30-day streak",                   cond:s=>s.streak>=30},
  {id:"streak_90", icon:"💥",name:"Inferno",          desc:"90-day streak",                   cond:s=>s.streak>=90},
  {id:"hrs_100",   icon:"⏱",name:"100 Hours",        desc:"Log 100 total hours",             cond:s=>totalHrs(s)>=100},
  {id:"hrs_500",   icon:"🕐",name:"500 Hours",        desc:"Log 500 total hours",             cond:s=>totalHrs(s)>=500},
  {id:"hrs_1000",  icon:"🕰",name:"1000 Hours",       desc:"Half the journey",               cond:s=>totalHrs(s)>=1000},
  {id:"phase1",    icon:"🌌",name:"Foundation Built", desc:"Complete Phase 1 (Day 90)",       cond:s=>s.day>90},
  {id:"phase2",    icon:"⭐",name:"Core Mastered",    desc:"Complete Phase 2 (Day 240)",      cond:s=>s.day>240},
  {id:"phase3",    icon:"🌟",name:"Advanced Complete",desc:"Complete Phase 3 (Day 360)",      cond:s=>s.day>360},
  {id:"phase4",    icon:"🏆",name:"IOAA Gold",        desc:"Complete all 450 days",           cond:s=>s.day>=450},
  {id:"rank_d",    icon:"🟢",name:"Rank D",           desc:"Reach 200 XP",                   cond:s=>s.xp>=200},
  {id:"rank_c",    icon:"🔵",name:"Rank C",           desc:"Reach 600 XP",                   cond:s=>s.xp>=600},
  {id:"rank_b",    icon:"🟣",name:"Rank B",           desc:"Reach 1200 XP",                  cond:s=>s.xp>=1200},
  {id:"rank_a",    icon:"🟠",name:"Rank A",           desc:"Reach 2400 XP",                  cond:s=>s.xp>=2400},
  {id:"rank_s",    icon:"✨",name:"Rank S: IOAA Gold",desc:"Reach 4000 XP",                  cond:s=>s.xp>=4000},
];

/* ---------- page configuration ---------- */
window.CONFIG = {
  subject: 'IOAA',
  storageKey: 'ioaa-sys',
  publishKey: 'olympiad.progress.ioaa',
  journalName: 'Journal',
  maxRankLabel: 'MAX RANK',
  totalDays: 450,
  curriculum: CURRICULUM,
  taskTemplates: [
    { text: "Theory — {A}",                                   dur: "1h 30m", xp: 20 },
    { text: "Derive from memory — {A}, no peeking",            dur: "45m",    xp: 15 },
    { text: "Problems — {B}, easy → IOAA level",               dur: "1h",     xp: 25 },
    { text: "Read/watch — {R}",                                dur: "30m",    xp: 10 },
    { text: "Observation — Stellarium, 15 min of sky practice", dur: "15m",   xp: 10 },
    { text: "Journal — what clicked on {W}, what's still murky", dur: "5m",   xp: 10 }
  ],
  ranks: RANKS,
  achievements: ACHIEVEMENTS,
  phases: [
    { name: 'Foundation',        from: 1,   to: 90  },
    { name: 'Core Astrophysics', from: 91,  to: 240 },
    { name: 'Advanced + Data',   from: 241, to: 360 },
    { name: 'Peak Performance',  from: 361, to: 450 }
  ],
  tracks: [
    { key: 'pos',      label: 'Positional Astro',  span: 77, offset: 14  },
    { key: 'photo',    label: 'Photometry',        span: 28, offset: 63  },
    { key: 'mech',     label: 'Celestial Mech',    span: 70, offset: 91  },
    { key: 'stellar',  label: 'Stellar Astro',     span: 77, offset: 161 },
    { key: 'galactic', label: 'Galactic + Cosmo',  span: 63, offset: 238 },
    { key: 'papers',   label: 'Past Papers',       span: 93, offset: 232 }
  ]
};
